name: CI

on:
  push:
    branches:
    - main
    
jobs:
  
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Connect to host via SSH and update containers
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          command: |
            [ ! -d orgs-farming] || git clone https://github.com/orgs-selector/orgs_farming
            cd orgs_farming
            
            docker-compose down
            docker container prune -f
            
            git pull
            
            docker-compose up -d --build
